#!/usr/bin/env python
import os
import sys

relative_paste = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'paste')

if os.path.exists(relative_paste):
    sys.path.insert(0, os.path.dirname(relative_paste))

from paste.script import command
command.run()
