name: tests
on:
- push
- pull_request
- workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                - python: 3.7
                  toxenv: py37
                - python: 3.8
                  toxenv: py38
                - python: 3.9
                  toxenv: py39
                - python: "3.10"
                  toxenv: py310
                - python: "3.11"
                  toxenv: py311
                - python: "3.12"
                  toxenv: py312
                - python: "3.13"
                  toxenv: py313
        name: ${{ matrix.toxenv }} on Python ${{ matrix.python }}
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
              python-version: ${{ matrix.python }}
        - run: pip install tox
        - run: tox
          env:
              TOXENV: ${{ matrix.toxenv }}
